"""Diff two `list-index.json` generations and render a human-readable changelog entry.

A contributor who proposed a list (or flagged an item, see `tools/intake.py`) has no way to tell
whether their submission actually changed the published catalogue. This is a pure, deterministic
diff over two already-validated index JSON documents (no network, no re-classification) plus a
Markdown renderer, so a maintainer can run it after every `tools.lists publish` and append the
result to `docs/demo/catalogue-changelog.md`.

    python -m tools.changelog --before-ref <git-ref> --after data/list-index.json
    python -m tools.changelog --before <path> --after <path>  # explicit files
"""
from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHANGELOG_PATH = ROOT / "docs/demo/catalogue-changelog.md"

# Fields whose change is worth surfacing for an already-published, still-published entry.
TRACKED_FIELDS = ("state", "reason", "stars")


def _index_by_id(index: dict) -> dict:
    return {item["id"]: item for item in index.get("lists", [])}


def diff_indexes(before: dict, after: dict) -> dict:
    """Pure diff over two index documents; never mutates its inputs."""
    before_by_id, after_by_id = _index_by_id(before), _index_by_id(after)
    before_ids, after_ids = set(before_by_id), set(after_by_id)

    added = [after_by_id[i] for i in sorted(after_ids - before_ids, key=lambda i: after_by_id[i]["name"].casefold())]
    removed = [before_by_id[i] for i in sorted(before_ids - after_ids, key=lambda i: before_by_id[i]["name"].casefold())]

    changed = []
    for list_id in sorted(before_ids & after_ids, key=lambda i: after_by_id[i]["name"].casefold()):
        before_item, after_item = before_by_id[list_id], after_by_id[list_id]
        deltas = {field: {"before": before_item.get(field), "after": after_item.get(field)}
                  for field in TRACKED_FIELDS if before_item.get(field) != after_item.get(field)}
        if deltas:
            changed.append({"id": list_id, "name": after_item["name"], "url": after_item["url"], "deltas": deltas})

    return {
        "before_generated_at": before.get("generated_at"), "after_generated_at": after.get("generated_at"),
        "before_run_id": before.get("run_id"), "after_run_id": after.get("run_id"),
        "before_digest": before.get("digest"), "after_digest": after.get("digest"),
        "added": added, "removed": removed, "changed": changed,
    }


def render(diff: dict) -> str:
    """Deterministic Markdown for one changelog entry: same inputs always produce the same text."""
    lines = [f"## {diff['after_run_id']} ({diff['after_generated_at']})", "",
             f"Compared against `{diff['before_run_id']}` ({diff['before_generated_at']}); "
             f"digest `{diff['before_digest']}` -> `{diff['after_digest']}`.", ""]

    if diff["added"]:
        lines.append(f"### Added ({len(diff['added'])})")
        lines.append("")
        for item in diff["added"]:
            lines.append(f"- [{item['name']}]({item['url']}) — {item['state']}: {item['reason']}")
        lines.append("")

    if diff["removed"]:
        lines.append(f"### Removed ({len(diff['removed'])})")
        lines.append("")
        for item in diff["removed"]:
            lines.append(f"- [{item['name']}]({item['url']}) — was {item['state']}: {item['reason']}")
        lines.append("")

    if diff["changed"]:
        lines.append(f"### Changed ({len(diff['changed'])})")
        lines.append("")
        for item in diff["changed"]:
            parts = [f"{field} {delta['before']!r} -> {delta['after']!r}" for field, delta in item["deltas"].items()]
            lines.append(f"- [{item['name']}]({item['url']}) — " + "; ".join(parts))
        lines.append("")

    if not (diff["added"] or diff["removed"] or diff["changed"]):
        lines.append("No catalogue changes in this publish.")
        lines.append("")

    return "\n".join(lines)


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _load_from_ref(ref: str, relative_path: str, root: Path) -> dict:
    result = subprocess.run(["git", "show", f"{ref}:{relative_path}"], cwd=root,
                             capture_output=True, text=True, encoding="utf-8", timeout=60)
    if result.returncode != 0:
        raise RuntimeError(f"git show {ref}:{relative_path} failed: {result.stderr.strip()}")
    return json.loads(result.stdout)


def append_changelog(entry: str, path: Path = CHANGELOG_PATH) -> None:
    """Newest-first, append-only: new entries go right after the top-level heading."""
    heading = "# Catalogue changelog\n\nHuman-readable diff of what changed between publications, generated by `python -m tools.changelog`. Newest entries first.\n"
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if existing.startswith(heading):
            body = existing[len(heading):]
        else:
            body = existing
    else:
        body = ""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(heading + "\n" + entry + "\n" + body, encoding="utf-8")


def main(argv: list[str] | None = None) -> dict:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--before", help="Path to the earlier list-index.json (mutually exclusive with --before-ref).")
    parser.add_argument("--before-ref", help="Git ref to read data/list-index.json from (mutually exclusive with --before).")
    parser.add_argument("--after", default=str(ROOT / "data/list-index.json"), help="Path to the newer list-index.json.")
    parser.add_argument("--write", action="store_true", help="Append the rendered entry to docs/demo/catalogue-changelog.md.")
    args = parser.parse_args(argv)

    if bool(args.before) == bool(args.before_ref):
        parser.error("exactly one of --before or --before-ref is required")

    before = _load_json(Path(args.before)) if args.before else _load_from_ref(args.before_ref, "data/list-index.json", ROOT)
    after = _load_json(Path(args.after))

    diff = diff_indexes(before, after)
    entry = render(diff)
    print(entry)
    if args.write:
        append_changelog(entry)
    return diff


if __name__ == "__main__":
    main()
