[theme]
base = "light"
primaryColor = "#087f73"
backgroundColor = "#faf8f2"
secondaryBackgroundColor = "#eeeee5"
textColor = "#182d2b"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
